# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
print(OUTPUT_PATH)
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/frame1")
print(ASSETS_PATH)

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1000x600")
window.configure(bg="#FFFFFF")

canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=600,
    width=1000,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    500.0,
    301.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=547.0,
    y=390.88629150390625,
    width=405.0,
    height=55.846160888671875
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=668.4073486328125,
    y=510.6722412109375,
    width=162.185302734375,
    height=28.3277587890625
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    749.5,
    154.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=582.0,
    y=137.0,
    width=335.0,
    height=33.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    749.5,
    242.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=582.0,
    y=225.0,
    width=335.0,
    height=33.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    749.5,
    330.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=582.0,
    y=313.0,
    width=335.0,
    height=33.0
)

canvas.create_text(
    664.0,
    61.0,
    anchor="nw",
    text="Register",
    fill="#A1A1A1",
    font=("ArialMT", 30 * -1)
)

canvas.create_text(
    582.0,
    105.0,
    anchor="nw",
    text="Username",
    fill="#8E8E8E",
    font=("ArialMT", 14 * -1)
)

canvas.create_text(
    582.0,
    193.0,
    anchor="nw",
    text="Password",
    fill="#8E8E8E",
    font=("ArialMT", 14 * -1)
)

canvas.create_text(
    582.0,
    282.0,
    anchor="nw",
    text="Confirm Password",
    fill="#8E8E8E",
    font=("ArialMT", 14 * -1)
)

canvas.create_text(
    649.0,
    473.0,
    anchor="nw",
    text="Already have an account?",
    fill="#8E8E8E",
    font=("ArialMT", 14 * -1)
)

canvas.create_text(
    116.0,
    293.0,
    anchor="nw",
    text="Face Recognition\nStudent Identifier",
    fill="#FFFFFF",
    font=("Arial BoldMT", 32 * -1)
)
window.resizable(False, False)
window.mainloop()
