
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1000x600")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 1000,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    500.0,
    300.0,
    image=image_image_1
)

canvas.create_text(
    264.0,
    33.0,
    anchor="nw",
    text="Student Information",
    fill="#FFFFFF",
    font=("Arial BoldMT", 48 * -1)
)

canvas.create_text(
    25.0,
    238.0,
    anchor="nw",
    text="BSCS",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    31.0,
    343.0,
    anchor="nw",
    text="Course Code:",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    484.0,
    213.0,
    anchor="nw",
    text="Course Code",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    484.0,
    253.0,
    anchor="nw",
    text="Course Code",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    659.0,
    253.0,
    anchor="nw",
    text="Course Code",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    828.0,
    253.0,
    anchor="nw",
    text="Course Code",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    688.0,
    213.0,
    anchor="nw",
    text="Time",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    851.0,
    213.0,
    anchor="nw",
    text="Day",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    31.0,
    392.0,
    anchor="nw",
    text="Date:",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    197.0,
    392.0,
    anchor="nw",
    text="March 1, 2023",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    197.0,
    419.0,
    anchor="nw",
    text="Thursday",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    197.0,
    446.0,
    anchor="nw",
    text="10:45:23 AM",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    197.0,
    495.0,
    anchor="nw",
    text="10:45:23 AM",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    197.0,
    544.0,
    anchor="nw",
    text="10:45:23 AM",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    31.0,
    419.0,
    anchor="nw",
    text="Day:",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    31.0,
    446.0,
    anchor="nw",
    text="Time:",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    30.0,
    495.0,
    anchor="nw",
    text="Time in:",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    31.0,
    544.0,
    anchor="nw",
    text="Time out:",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    197.0,
    343.0,
    anchor="nw",
    text="CS202",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    25.0,
    145.0,
    anchor="nw",
    text="Firstname, Lastname",
    fill="#FFFFFF",
    font=("Arial BoldMT", 32 * -1)
)

canvas.create_text(
    25.0,
    277.0,
    anchor="nw",
    text="3-CS1",
    fill="#FFFFFF",
    font=("Arial BoldMT", 20 * -1)
)

canvas.create_text(
    25.0,
    196.0,
    anchor="nw",
    text="2023-00100",
    fill="#FFFFFF",
    font=("Arial BoldMT", 22 * -1)
)

canvas.create_text(
    659.0,
    153.0,
    anchor="nw",
    text="Schedule",
    fill="#FFFFFF",
    font=("Arial BoldMT", 24 * -1)
)

canvas.create_rectangle(
    172.0,
    340.0,
    174.0,
    578.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    466.0,
    198.0,
    957.0,
    200.0,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
